/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DNAHashProbeInterface extends Interface {
  getFunction(
    nameOrSignature: "computeDnaHash" | "computeGameMonsterIdHash"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "computeDnaHash",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "computeGameMonsterIdHash",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "computeDnaHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeGameMonsterIdHash",
    data: BytesLike
  ): Result;
}

export interface DNAHashProbe extends BaseContract {
  connect(runner?: ContractRunner | null): DNAHashProbe;
  waitForDeployment(): Promise<this>;

  interface: DNAHashProbeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  computeDnaHash: TypedContractMethod<
    [
      hpGene: BigNumberish,
      attackGene: BigNumberish,
      defenseGene: BigNumberish,
      speedGene: BigNumberish,
      mutationGene: BigNumberish
    ],
    [string],
    "view"
  >;

  computeGameMonsterIdHash: TypedContractMethod<[id: string], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "computeDnaHash"
  ): TypedContractMethod<
    [
      hpGene: BigNumberish,
      attackGene: BigNumberish,
      defenseGene: BigNumberish,
      speedGene: BigNumberish,
      mutationGene: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "computeGameMonsterIdHash"
  ): TypedContractMethod<[id: string], [string], "view">;

  filters: {};
}
