/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMonsterNFT,
  IMonsterNFTInterface,
} from "../../../contracts/interfaces/IMonsterNFT";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "previousURI",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "newURI",
        type: "string",
      },
    ],
    name: "BaseURIUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "previousSpeciesId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "uint32",
        name: "newSpeciesId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "previousStage",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "newStage",
        type: "uint8",
      },
    ],
    name: "MonsterEvolved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "gameMonsterIdHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "speciesId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "generation",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "rarity",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "evolutionStage",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "dnaHash",
        type: "bytes32",
      },
    ],
    name: "MonsterMinted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "newSpeciesId",
        type: "uint32",
      },
      {
        internalType: "uint8",
        name: "newEvolutionStage",
        type: "uint8",
      },
    ],
    name: "evolveMonster",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getMonster",
    outputs: [
      {
        components: [
          {
            internalType: "uint32",
            name: "speciesId",
            type: "uint32",
          },
          {
            internalType: "uint16",
            name: "generation",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "rarity",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "evolutionStage",
            type: "uint8",
          },
          {
            internalType: "bytes32",
            name: "dnaHash",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "gameMonsterIdHash",
            type: "bytes32",
          },
        ],
        internalType: "struct IMonsterNFT.MonsterData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "gameMonsterIdHash",
        type: "bytes32",
      },
    ],
    name: "getTokenIdByGameMonsterIdHash",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "gameMonsterIdHash",
        type: "bytes32",
      },
    ],
    name: "isGameMonsterMinted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "gameMonsterIdHash",
            type: "bytes32",
          },
          {
            internalType: "uint32",
            name: "speciesId",
            type: "uint32",
          },
          {
            internalType: "uint16",
            name: "generation",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "rarity",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "evolutionStage",
            type: "uint8",
          },
          {
            internalType: "bytes32",
            name: "dnaHash",
            type: "bytes32",
          },
        ],
        internalType: "struct IMonsterNFT.MintMonsterInput",
        name: "monster",
        type: "tuple",
      },
    ],
    name: "mintMonster",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMonsterNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IMonsterNFTInterface {
    return new Interface(_abi) as IMonsterNFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMonsterNFT {
    return new Contract(address, _abi, runner) as unknown as IMonsterNFT;
  }
}
