/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IMonsterNFT {
  export type MonsterDataStruct = {
    speciesId: BigNumberish;
    generation: BigNumberish;
    rarity: BigNumberish;
    evolutionStage: BigNumberish;
    dnaHash: BytesLike;
    gameMonsterIdHash: BytesLike;
  };

  export type MonsterDataStructOutput = [
    speciesId: bigint,
    generation: bigint,
    rarity: bigint,
    evolutionStage: bigint,
    dnaHash: string,
    gameMonsterIdHash: string
  ] & {
    speciesId: bigint;
    generation: bigint;
    rarity: bigint;
    evolutionStage: bigint;
    dnaHash: string;
    gameMonsterIdHash: string;
  };

  export type MintMonsterInputStruct = {
    gameMonsterIdHash: BytesLike;
    speciesId: BigNumberish;
    generation: BigNumberish;
    rarity: BigNumberish;
    evolutionStage: BigNumberish;
    dnaHash: BytesLike;
  };

  export type MintMonsterInputStructOutput = [
    gameMonsterIdHash: string,
    speciesId: bigint,
    generation: bigint,
    rarity: bigint,
    evolutionStage: bigint,
    dnaHash: string
  ] & {
    gameMonsterIdHash: string;
    speciesId: bigint;
    generation: bigint;
    rarity: bigint;
    evolutionStage: bigint;
    dnaHash: string;
  };
}

export interface IMonsterNFTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "evolveMonster"
      | "getMonster"
      | "getTokenIdByGameMonsterIdHash"
      | "isGameMonsterMinted"
      | "mintMonster"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BaseURIUpdated"
      | "MonsterEvolved"
      | "MonsterMinted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "evolveMonster",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMonster",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenIdByGameMonsterIdHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isGameMonsterMinted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintMonster",
    values: [AddressLike, IMonsterNFT.MintMonsterInputStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "evolveMonster",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMonster", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenIdByGameMonsterIdHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGameMonsterMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintMonster",
    data: BytesLike
  ): Result;
}

export namespace BaseURIUpdatedEvent {
  export type InputTuple = [previousURI: string, newURI: string];
  export type OutputTuple = [previousURI: string, newURI: string];
  export interface OutputObject {
    previousURI: string;
    newURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MonsterEvolvedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    previousSpeciesId: BigNumberish,
    newSpeciesId: BigNumberish,
    previousStage: BigNumberish,
    newStage: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    previousSpeciesId: bigint,
    newSpeciesId: bigint,
    previousStage: bigint,
    newStage: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    previousSpeciesId: bigint;
    newSpeciesId: bigint;
    previousStage: bigint;
    newStage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MonsterMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    owner: AddressLike,
    gameMonsterIdHash: BytesLike,
    speciesId: BigNumberish,
    generation: BigNumberish,
    rarity: BigNumberish,
    evolutionStage: BigNumberish,
    dnaHash: BytesLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    owner: string,
    gameMonsterIdHash: string,
    speciesId: bigint,
    generation: bigint,
    rarity: bigint,
    evolutionStage: bigint,
    dnaHash: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    owner: string;
    gameMonsterIdHash: string;
    speciesId: bigint;
    generation: bigint;
    rarity: bigint;
    evolutionStage: bigint;
    dnaHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IMonsterNFT extends BaseContract {
  connect(runner?: ContractRunner | null): IMonsterNFT;
  waitForDeployment(): Promise<this>;

  interface: IMonsterNFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  evolveMonster: TypedContractMethod<
    [
      tokenId: BigNumberish,
      newSpeciesId: BigNumberish,
      newEvolutionStage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getMonster: TypedContractMethod<
    [tokenId: BigNumberish],
    [IMonsterNFT.MonsterDataStructOutput],
    "view"
  >;

  getTokenIdByGameMonsterIdHash: TypedContractMethod<
    [gameMonsterIdHash: BytesLike],
    [bigint],
    "view"
  >;

  isGameMonsterMinted: TypedContractMethod<
    [gameMonsterIdHash: BytesLike],
    [boolean],
    "view"
  >;

  mintMonster: TypedContractMethod<
    [to: AddressLike, monster: IMonsterNFT.MintMonsterInputStruct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "evolveMonster"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      newSpeciesId: BigNumberish,
      newEvolutionStage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMonster"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [IMonsterNFT.MonsterDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenIdByGameMonsterIdHash"
  ): TypedContractMethod<[gameMonsterIdHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isGameMonsterMinted"
  ): TypedContractMethod<[gameMonsterIdHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintMonster"
  ): TypedContractMethod<
    [to: AddressLike, monster: IMonsterNFT.MintMonsterInputStruct],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "BaseURIUpdated"
  ): TypedContractEvent<
    BaseURIUpdatedEvent.InputTuple,
    BaseURIUpdatedEvent.OutputTuple,
    BaseURIUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MonsterEvolved"
  ): TypedContractEvent<
    MonsterEvolvedEvent.InputTuple,
    MonsterEvolvedEvent.OutputTuple,
    MonsterEvolvedEvent.OutputObject
  >;
  getEvent(
    key: "MonsterMinted"
  ): TypedContractEvent<
    MonsterMintedEvent.InputTuple,
    MonsterMintedEvent.OutputTuple,
    MonsterMintedEvent.OutputObject
  >;

  filters: {
    "BaseURIUpdated(string,string)": TypedContractEvent<
      BaseURIUpdatedEvent.InputTuple,
      BaseURIUpdatedEvent.OutputTuple,
      BaseURIUpdatedEvent.OutputObject
    >;
    BaseURIUpdated: TypedContractEvent<
      BaseURIUpdatedEvent.InputTuple,
      BaseURIUpdatedEvent.OutputTuple,
      BaseURIUpdatedEvent.OutputObject
    >;

    "MonsterEvolved(uint256,uint32,uint32,uint8,uint8)": TypedContractEvent<
      MonsterEvolvedEvent.InputTuple,
      MonsterEvolvedEvent.OutputTuple,
      MonsterEvolvedEvent.OutputObject
    >;
    MonsterEvolved: TypedContractEvent<
      MonsterEvolvedEvent.InputTuple,
      MonsterEvolvedEvent.OutputTuple,
      MonsterEvolvedEvent.OutputObject
    >;

    "MonsterMinted(uint256,address,bytes32,uint32,uint16,uint8,uint8,bytes32)": TypedContractEvent<
      MonsterMintedEvent.InputTuple,
      MonsterMintedEvent.OutputTuple,
      MonsterMintedEvent.OutputObject
    >;
    MonsterMinted: TypedContractEvent<
      MonsterMintedEvent.InputTuple,
      MonsterMintedEvent.OutputTuple,
      MonsterMintedEvent.OutputObject
    >;
  };
}
