/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  DNAHashProbe,
  DNAHashProbeInterface,
} from "../../../contracts/test/DNAHashProbe";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "hpGene",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "attackGene",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "defenseGene",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "speedGene",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "mutationGene",
        type: "uint32",
      },
    ],
    name: "computeDnaHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "id",
        type: "string",
      },
    ],
    name: "computeGameMonsterIdHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b5061020a8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c8063a8078c7c14610038578063b01c663a1461005d575b5f5ffd5b61004b6100463660046100de565b6100bd565b60405190815260200160405180910390f35b61004b61006b366004610164565b6040805163ffffffff968716602080830191909152958716818301529386166060850152918516608084015290931660a0808301919091528351808303909101815260c0909101909252815191012090565b5f82826040516100ce9291906101c5565b6040518091039020905092915050565b5f5f602083850312156100ef575f5ffd5b823567ffffffffffffffff811115610105575f5ffd5b8301601f81018513610115575f5ffd5b803567ffffffffffffffff81111561012b575f5ffd5b85602082840101111561013c575f5ffd5b6020919091019590945092505050565b803563ffffffff8116811461015f575f5ffd5b919050565b5f5f5f5f5f60a08688031215610178575f5ffd5b6101818661014c565b945061018f6020870161014c565b935061019d6040870161014c565b92506101ab6060870161014c565b91506101b96080870161014c565b90509295509295909350565b818382375f910190815291905056fea26469706673582212204500c882c54fb4a5d059d7ea026fcf4bb46f0a3b801f300698df6b15a44cd91364736f6c634300081c0033";

type DNAHashProbeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DNAHashProbeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DNAHashProbe__factory extends ContractFactory {
  constructor(...args: DNAHashProbeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DNAHashProbe & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DNAHashProbe__factory {
    return super.connect(runner) as DNAHashProbe__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DNAHashProbeInterface {
    return new Interface(_abi) as DNAHashProbeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DNAHashProbe {
    return new Contract(address, _abi, runner) as unknown as DNAHashProbe;
  }
}
